# Spring boot application
spring:
  application:
    name: dubbo-provider-two
  profiles:
    active: dev

# Dubbo Config properties
dubbo:
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 21002
    status: server
  ## RegistryConfig Bean
  registry:
    id: dubbo-provider-two-registry
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
  # Base packages to scan Dubbo Comptwonts (e.g @Service , @Reference)
  scan:
    basePackages: net.lovexq.example.dubbo.two.facade.impl
  # ProviderConfig Bean
  provider:
    group: ${spring.profiles.active}
    version: 1.0.0
    timeout: 30000
    retries: 0
    delay: -1
    filter:

logging:
  file:
    name: ${spring.application.name}
    path: /home/lovexq/${spring.application.name}/logs
  #level: OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    root: INFO
    org.apache.dubbo: INFO
    net.lovexq.example: INFO
    org.apache.zookeeper: WARN
    org.springframework: WARN
    org.springframework.boot: INFO