# Spring boot application
spring:
  application:
    name: dubbo-consumer-one
  profiles:
    active: dev

server:
  port: 8188

management:
  port: 8189

# Dubbo Config properties
dubbo:
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 21000
  ## RegistryConfig Bean
  registry:
    id: dubbo-consumer-one-registry
    address: zookeeper://server3:2181,server4:2181,server5:2181
    simplified: true
  consumer:
    check: false
    filter: rpcLogFilter2
  service:
    provider-one:
      group: ${spring.profiles.active}
      version: 1.0.0
      #url: dubbo://127.0.0.1:21000
    provider-two:
      group: ${spring.profiles.active}
      version: 1.0.0
      #url: dubbo://127.0.0.1:21001

logging:
  file:
    name: ${spring.application.name}
    path: /home/lovexq/${spring.application.name}/logs
  #level: OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    root: INFO
    org.apache.dubbo: INFO
    net.lovexq.example: INFO
    org.apache.zookeeper: WARN
    org.springframework: WARN
    org.springframework.boot: INFO