# Spring boot application
spring:
  application:
    name: dubbo-consumer-one

server:
  port: 8080

management:
  port: 8081

# Service version
demo:
  service:
    version: 1.0.0

# Dubbo Config properties
dubbo:
  ## ApplicationConfig Bean
  application:
    id: dubbo-consumer-one-id
    name: dubbo-consumer-one-name
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345