# Spring boot application
spring:
  application:
    name: dubbo-consumer-one

server:
  port: 8088

management:
  port: 8089

# Dubbo Config properties
dubbo:
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 21000
  ## RegistryConfig Bean
  registry:
    id: dubbo-consumer-one-registry
    address: zookeeper://127.0.0.1:2181
  consumer:
      check: false
      filter: rpcLogFilter2
  service:
    provider-one:
      group: dev
      version: 1.0.0
      #url: dubbo://127.0.0.1:21000
    provider-two:
      group: dev
      version: 1.0.0
      #url: dubbo://127.0.0.1:21001

logging:
  path: /home/net/lovexq/dubbo-provider-two/log/${spring.application.name}-${server.port}
  file: ${logging.path}/application.log
  #level: OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    root: INFO
    com.alibaba.dubbo: INFO
    net.lovexq.example: INFO
    org.apache.zookeeper: WARN
    org.springframework: WARN
    org.springframework.boot: INFO