# Spring boot application
spring:
  application:
    name: dubbo-provider-one

server:
  port: 9090

management:
  port: 9091

# Service version
demo:
  service:
    version: 1.0.0

# Dubbo Config properties
dubbo:
  ## ApplicationConfig Bean
  application:
    id: dubbo-provider-one-id
    name: dubbo-provider-one-name
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  ## RegistryConfig Bean
  registry:
    address: N/A
    id: my-registry
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: net.lovexq.example.dubbo.one.facade.impl
