# Spring boot application
spring:
  application:
    name: dubbo-provider-one

server:
  port: 9090

management:
  port: 9091

# Dubbo Config properties
dubbo:
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 21000
    status: server
  ## RegistryConfig Bean
  registry:
    id: dubbo-provider-one-registry
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: net.lovexq.example.dubbo.one.facade.impl
  # ProviderConfig Bean
  provider:
    group: dev
    version: 1.0.0
    timeout: 300000
    retries: 0
    delay: 100
    #filter:
  service:
    provider-two:
      group: dev
      version: 1.0.0
      #url: dubbo://127.0.0.1:21001

logging:
  path: /home/net/lovexq/dubbo-provider-one/log/${spring.application.name}-${server.port}
  file: ${logging.path}/application.log
  #level: OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    root: INFO
    com.alibaba.dubbo: INFO
    net.lovexq.example: INFO
    org.apache.zookeeper: WARN
    org.springframework: WARN
    org.springframework.boot: INFO