# Spring boot application
spring:
  application:
    name: dubbo-provider-one
  profiles:
    active: dev

# Dubbo Config properties
dubbo:
  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
  scan:
    basePackages: net.lovexq.example.dubbo.one.facade.impl
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 21001
    status: server
  ## RegistryConfig Bean
  registry:
    id: dubbo-provider-one-registry
    address: zookeeper://server3:2181,server4:2181,server5:2181
    simplified: true
  consumer:
    check: false
  # ProviderConfig Bean
  provider:
    group: ${spring.profiles.active}
    version: 1.0.0
    timeout: 30000
    retries: 0
    delay: -1
    #filter:
  service:
    provider-two:
      group: ${spring.profiles.active}
      version: 1.0.0
      #url: dubbo://127.0.0.1:21001

logging:
  file:
    name: ${spring.application.name}
    path: /home/lovexq/${spring.application.name}/logs
  #level: OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    root: INFO
    org.apache.dubbo: INFO
    net.lovexq.example: INFO
    org.apache.zookeeper: WARN
    org.springframework: WARN
    org.springframework.boot: INFO